create table flightinfo  (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	sid INT NOT NULL,
	aid INT NOT NULL,
	hex CHAR(10),
	fid INT NOT NULL,
	cs CHAR(10),
	alt INT NOT NULL,
	gs INT NOT NULL,
	trk INT NOT NULL,
	lat CHAR(12),
	lan CHAR(12),
	vr INT,
	sq INT,
	alrt INT,
	emer INT,
	spi INT,
	gnd INT,
	created DATETIME,
	updated DATETIME) ENGINE=INNODB;
